on: push
name: Deploy on Now
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --public --no-clipboard deploy ./ > $HOME/${{ github.action }}.txt
    - name: sha-alias
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias `cat $HOME/${{ github.action }}.txt` ${{ github.sha }}
    - name: svelte-branch-filter
      uses: actions/bin/filter@master
      with:
        args: branch svelte
    - name: master-branch-filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: svelte-alias
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias `cat $HOME/${{ github.action }}.txt` svelte.madebysid.com
    - name: release
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias --local-config=./now.json
