on:
  push:
    branches:
      - develop
name: Deploy develop
jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install
      - name: deploy
        run: npm run deploy
