on:
  push:
    branches:
      - master
name: Deploy master
jobs:
  deploy-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install
      - name: deploy
        run: npm run deploy
